### PR TITLE
Add comparison methods to Individual

### PR DESCRIPTION
**Pull request by hgrif**
This makes it easy to compare Individuals with each other (see unit test) or in an iterable (see line 84 of `population.py`).

This is more an idea than a finalized proposal (I didn't test it thoroughly), so discuss before thinking of merging. ;)

### CODE REVIEW

**Comment by koaning** [comment]
Thanks @hgrif! I certainly do not mind having this, though the feature will be internal mostly. 

I only wonder about some edge cases of base behaviour. Internally we have an `.evaluate()` mechanic that allows an individual to not be evaluated. If an individual gets two mutations in a row then we usually only want the expensive evaluation to occur on the last mutation and not on the first. 

What would be good behavior if one, or both, of the individuals aren't evaluated? 

When two individuals are currently unevaluated, they suggest having an equal fitness (which is bad).

**Comment by rogiervandergeer** [comment]
I like this, thanks Henk.

On the other hand, I'm scared this may lead to confusion in some rare cases. Suppose someone is looking to see whether a certain individual is still in the population after some iterations. He might do `individual in population`, which will return `True` if there is any individual with the same fitness. @koaning do you see this as a problem?

**Comment by koaning** [comment]
mhm. it does bother me a bit. but this brings up a different question... two individuals with identical chromosomes and fitness ... should they ever evaluate to not equal?

**Comment by rogiervandergeer** [comment]
That depends... what if their ages aren't equal? This needs some discussion

**Comment by koaning** [comment]
@rogiervandergeer do we still want to add this? if not, we might need to consider removing the merge request.

**Pull request closed without merging**
