### PR TITLE
Azure Pipeline impl

### PR DESCRIPTION
**Pull request by NielsZeilemaker**

### CODE REVIEW

**Comment by koaning** [comment]
@rogiervandergeer I've been revoken access to the settings of this repo. That means that I can no longer turn off travis. Could you have a look? I noticed some renewed interest in this library during this years PyData challenge so I wouldn't mind cleanin up some of the docs.

**Comment by NielsZeilemaker** [comment]
Hi @koaning I've send you an invite to give you write access months ago when I revoked your access. It's still pending I see. Wrt travis, travis was given access to our github org, which I cannot simply revoke, as I don't know if other repo's are using it. Disabling a single repo has to be done from the travis side. Do you still have access to it?

**Comment by koaning** [comment]
@NielsZeilemaker that's strange. I've just search through my email, found the invite and got this; 

image

Could you send it again?

**Comment by koaning** [comment]
@rogiervandergeer I've been made an owner once again but I think I still do not have access to the project settings. This makes sense because that might allow me to delete this project. However somebody needs to go there to turn off the travis checking mechanism. Could you have a look?

**Comment by rogiervandergeer** [comment]
I don't see Travis mentioned anywhere in the settings. Where would this be?

**Comment by koaning** [comment]
I imagine travis still being listed here: 

image

That'd be one spot to check out there may be another one though.

**Comment by koaning** [comment]
I'm assuming travis is also listed as a step in the branch protection rules. Feel free to remove it there too. 

image

**Comment by rogiervandergeer** [comment]
I don't see any reference to Travis in either location

**Comment by rogiervandergeer** [comment]
Oh hold on - it was in the protection rules. I removed it

**Comment by koaning** [comment]
@rogiervandergeer could you perhaps merge this one manually then? You'd need to manually give yourself permission to merge this branch and if possible also remove the `.travis-ci.yml` file.

**Pull request merged**
